# Generated by Django 4.0.3 on 2022-04-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hospital_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
