# Generated by Django 4.0.3 on 2022-03-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='storages',
        ),
        migrations.AddField(
            model_name='donor',
            name='store_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.store'),
        ),
        migrations.AddField(
            model_name='item',
            name='store_name',
            field=models.ManyToManyField(related_name='name_of_store', to='tracker.store'),
        ),
        migrations.RemoveField(
            model_name='store',
            name='item',
        ),
        migrations.AddField(
            model_name='store',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='tracker.item'),
        ),
    ]
