# Generated by Django 4.0.3 on 2022-04-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='donor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
