# Generated by Django 4.0.3 on 2022-04-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_order_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
