# Generated by Django 4.0.3 on 2022-03-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_remove_item_storages_donor_store_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='donor',
            name='hospital_name',
            field=models.ForeignKey(default='Hospital', on_delete=django.db.models.deletion.CASCADE, to='tracker.hospital'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='store_name',
            field=models.ForeignKey(default='hospital', null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.store'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='store_name',
        ),
        migrations.AddField(
            model_name='item',
            name='store_name',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='name_of_store', to='tracker.store'),
        ),
    ]
