<<<<<<< HEAD:tracker/migrations/0002_order_status.py
# Generated by Django 4.0.3 on 2022-04-11 05:17
=======
# Generated by Django 4.0.3 on 2022-04-07 09:37
>>>>>>> f92830362f89ef1596dfee8ddd2621e16d656450:tracker/migrations/0003_order_status.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_order_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
<<<<<<< HEAD:tracker/migrations/0002_order_status.py
            field=models.CharField(default='pending', max_length=50),
=======
            field=models.BooleanField(null=True),
>>>>>>> f92830362f89ef1596dfee8ddd2621e16d656450:tracker/migrations/0003_order_status.py
        ),
    ]
