# Generated by Django 4.0.3 on 2022-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_registrations_remove_store_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
