# Generated by Django 4.0.3 on 2022-04-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
