# Generated by Django 4.0.3 on 2022-03-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_donor_hospital_name_donor_hospital_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='hospital_name',
            field=models.ForeignKey(default='0', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='tracker.hospital'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=255),
        ),
    ]
