# Generated by Django 4.0.3 on 2022-03-30 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_donor_hospital_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='price',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='donor_name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='item',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='store',
            name='item',
        ),
        migrations.CreateModel(
            name='Merger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='tracker.donor')),
                ('hospital_name', models.ForeignKey(default='0', max_length=255, on_delete=django.db.models.deletion.CASCADE, to='tracker.hospital')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.store')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='tracker.item')),
            ],
        ),
    ]
