# Generated by Django 4.0.3 on 2022-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_registrations_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='contact',
            field=models.CharField(default=1234, max_length=16),
        ),
    ]
