# Generated by Django 4.0.3 on 2022-03-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_merger_user'),
        ('tracker', '0005_remove_donor_hospital_name_remove_donor_price_and_more'),
    ]

    operations = [
    ]
