# Generated by Django 4.0.3 on 2022-04-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_registrations_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='contact',
            field=models.CharField(max_length=16),
        ),
    ]
